name: vartur_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  equatable: ^2.0.7
  http: ^1.3.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#3547a9"  # Background color
  image: assets/splash_screen.png  
  # branding: assets/branding.png  
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android_12:
    image: assets/splash_300_little_font.png
    icon_background_color: "#3547a9"    
    # branding: assets/branding.png       
    # branding_gravity: bottom  
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart
